from google import genai
from google.genai import types
import os
from dotenv import load_dotenv

load_dotenv()

def query_docs(query: str) -> str:
    """
    Queries the ingested documents using Google File Search to answer the user's question.
    
    Args:
        query: The question or query to ask about the documents.
        
    Returns:
        The answer generated by the model based on the documents.
    """
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        return "Error: GEMINI_API_KEY not found in environment variables."
    
    client = genai.Client(api_key=api_key)
    
    # Find the File Search Store
    target_store = None
    try:
        # We need to list stores to find the one we created
        # Note: There isn't a direct "get by display name" so we iterate given the scale is likely small
        # or we rely on the most recent one.
        stores = list(client.file_search_stores.list())
        matching_stores = [s for s in stores if s.display_name == 'DocuScout Store']
        
        if matching_stores:
             # Assuming the list might not be ordered, we should ideally sort. 
             # But for now, let's just pick the last one if default order is chronological, 
             # or actually, let's trust that the most recent test run was the last one created.
             # Better: invalid/empty stores might be an issue.
             # Let's just pick the first one and print it to debug if needed, 
             # but to be smarter:
             target_store = matching_stores[-1] # Try the last one found
        
        if not target_store:
            return "Error: 'DocuScout Store' not found. Please ask the FileReader agent to ingest documents first."
        
        print(f"Using File Search Store: {target_store.name}")
            
    except Exception as e:
        return f"Error listing File Search Stores: {e}"

    try:
        # Generate content using the File Search tool
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=query,
            config=types.GenerateContentConfig(
                tools=[
                    types.Tool(
                        file_search=types.FileSearch(
                            file_search_store_names=[target_store.name]
                        )
                    )
                ]
            )
        )
        return response.text
    except Exception as e:
        return f"Error generating answer: {e}"
